/*
  This class has been generated by the Code Generator
*/

package com.opentext.lovhandler;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class LOV_MAPPINGBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_LOV_ID = "LOV_ID";
    public final static String ATTR_BRANCH = "BRANCH";
    public final static String ATTR_LOB = "LOB";
    public final static String ATTR_BUSINESS_FUNCTION = "BUSINESS_FUNCTION";
    public final static String ATTR_PRODUCT = "PRODUCT";
    public final static String ATTR_OPERATION = "OPERATION";
    public final static String ATTR_FORM_NAME = "FORM_NAME";
    public final static String ATTR_FORM_FIELD_NAME = "FORM_FIELD_NAME";
    public final static String ATTR_FIELD_TYPE = "FIELD_TYPE";
    public final static String ATTR_BACKEND_VIEW_NAME = "BACKEND_VIEW_NAME";
    public final static String ATTR_OUTPUT_COLUMNS = "OUTPUT_COLUMNS";
    public final static String ATTR_CONDITION = "CONDITION";
    public final static String ATTR_GROUP_CLAUSE = "GROUP_CLAUSE";
    public final static String ATTR_ORDER_CLAUSE = "ORDER_CLAUSE";
    public final static String ATTR_FIELD_DEFINITION = "FIELD_DEFINITION";
    public final static String ATTR_SG_DN = "SG_DN";
    public final static String ATTR_STATUS = "STATUS";
    public final static String ATTR_ATTRIBUTE1 = "ATTRIBUTE1";
    public final static String ATTR_ATTRIBUTE2 = "ATTRIBUTE2";
    public final static String ATTR_ATTRIBUTE3 = "ATTRIBUTE3";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(LOV_MAPPING.class);
            s_classInfo.setTableName("LOV_MAPPING");
            s_classInfo.setUIDElements(new String[]{ATTR_LOV_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LOV_ID);
                ai.setJavaName(ATTR_LOV_ID);
                ai.setColumnName(ATTR_LOV_ID);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_LOV_ID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BRANCH);
                ai.setJavaName(ATTR_BRANCH);
                ai.setColumnName(ATTR_BRANCH);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BRANCH);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LOB);
                ai.setJavaName(ATTR_LOB);
                ai.setColumnName(ATTR_LOB);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LOB);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BUSINESS_FUNCTION);
                ai.setJavaName(ATTR_BUSINESS_FUNCTION);
                ai.setColumnName(ATTR_BUSINESS_FUNCTION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BUSINESS_FUNCTION);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT);
                ai.setJavaName(ATTR_PRODUCT);
                ai.setColumnName(ATTR_PRODUCT);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OPERATION);
                ai.setJavaName(ATTR_OPERATION);
                ai.setColumnName(ATTR_OPERATION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_OPERATION);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FORM_NAME);
                ai.setJavaName(ATTR_FORM_NAME);
                ai.setColumnName(ATTR_FORM_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FORM_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FORM_FIELD_NAME);
                ai.setJavaName(ATTR_FORM_FIELD_NAME);
                ai.setColumnName(ATTR_FORM_FIELD_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FORM_FIELD_NAME);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FIELD_TYPE);
                ai.setJavaName(ATTR_FIELD_TYPE);
                ai.setColumnName(ATTR_FIELD_TYPE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FIELD_TYPE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BACKEND_VIEW_NAME);
                ai.setJavaName(ATTR_BACKEND_VIEW_NAME);
                ai.setColumnName(ATTR_BACKEND_VIEW_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BACKEND_VIEW_NAME);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OUTPUT_COLUMNS);
                ai.setJavaName(ATTR_OUTPUT_COLUMNS);
                ai.setColumnName(ATTR_OUTPUT_COLUMNS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_OUTPUT_COLUMNS);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CONDITION);
                ai.setJavaName(ATTR_CONDITION);
                ai.setColumnName(ATTR_CONDITION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CONDITION);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_GROUP_CLAUSE);
                ai.setJavaName(ATTR_GROUP_CLAUSE);
                ai.setColumnName(ATTR_GROUP_CLAUSE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_GROUP_CLAUSE);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ORDER_CLAUSE);
                ai.setJavaName(ATTR_ORDER_CLAUSE);
                ai.setColumnName(ATTR_ORDER_CLAUSE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ORDER_CLAUSE);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FIELD_DEFINITION);
                ai.setJavaName(ATTR_FIELD_DEFINITION);
                ai.setColumnName(ATTR_FIELD_DEFINITION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FIELD_DEFINITION);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SG_DN);
                ai.setJavaName(ATTR_SG_DN);
                ai.setColumnName(ATTR_SG_DN);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SG_DN);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_STATUS);
                ai.setJavaName(ATTR_STATUS);
                ai.setColumnName(ATTR_STATUS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_STATUS);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ATTRIBUTE1);
                ai.setJavaName(ATTR_ATTRIBUTE1);
                ai.setColumnName(ATTR_ATTRIBUTE1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ATTRIBUTE1);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ATTRIBUTE2);
                ai.setJavaName(ATTR_ATTRIBUTE2);
                ai.setColumnName(ATTR_ATTRIBUTE2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ATTRIBUTE2);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ATTRIBUTE3);
                ai.setJavaName(ATTR_ATTRIBUTE3);
                ai.setColumnName(ATTR_ATTRIBUTE3);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ATTRIBUTE3);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public LOV_MAPPINGBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getLOV_ID()
    {
        return getIntProperty(ATTR_LOV_ID);
    }

    public void setLOV_ID(int value)
    {
        setProperty(ATTR_LOV_ID, value, 0);
    }

    public String getBRANCH()
    {
        return getStringProperty(ATTR_BRANCH);
    }

    public void setBRANCH(String value)
    {
        setProperty(ATTR_BRANCH, value, 0);
    }

    public String getLOB()
    {
        return getStringProperty(ATTR_LOB);
    }

    public void setLOB(String value)
    {
        setProperty(ATTR_LOB, value, 0);
    }

    public String getBUSINESS_FUNCTION()
    {
        return getStringProperty(ATTR_BUSINESS_FUNCTION);
    }

    public void setBUSINESS_FUNCTION(String value)
    {
        setProperty(ATTR_BUSINESS_FUNCTION, value, 0);
    }

    public String getPRODUCT()
    {
        return getStringProperty(ATTR_PRODUCT);
    }

    public void setPRODUCT(String value)
    {
        setProperty(ATTR_PRODUCT, value, 0);
    }

    public String getOPERATION()
    {
        return getStringProperty(ATTR_OPERATION);
    }

    public void setOPERATION(String value)
    {
        setProperty(ATTR_OPERATION, value, 0);
    }

    public String getFORM_NAME()
    {
        return getStringProperty(ATTR_FORM_NAME);
    }

    public void setFORM_NAME(String value)
    {
        setProperty(ATTR_FORM_NAME, value, 0);
    }

    public String getFORM_FIELD_NAME()
    {
        return getStringProperty(ATTR_FORM_FIELD_NAME);
    }

    public void setFORM_FIELD_NAME(String value)
    {
        setProperty(ATTR_FORM_FIELD_NAME, value, 0);
    }

    public String getFIELD_TYPE()
    {
        return getStringProperty(ATTR_FIELD_TYPE);
    }

    public void setFIELD_TYPE(String value)
    {
        setProperty(ATTR_FIELD_TYPE, value, 0);
    }

    public String getBACKEND_VIEW_NAME()
    {
        return getStringProperty(ATTR_BACKEND_VIEW_NAME);
    }

    public void setBACKEND_VIEW_NAME(String value)
    {
        setProperty(ATTR_BACKEND_VIEW_NAME, value, 0);
    }

    public String getOUTPUT_COLUMNS()
    {
        return getStringProperty(ATTR_OUTPUT_COLUMNS);
    }

    public void setOUTPUT_COLUMNS(String value)
    {
        setProperty(ATTR_OUTPUT_COLUMNS, value, 0);
    }

    public String getCONDITION()
    {
        return getStringProperty(ATTR_CONDITION);
    }

    public void setCONDITION(String value)
    {
        setProperty(ATTR_CONDITION, value, 0);
    }

    public String getGROUP_CLAUSE()
    {
        return getStringProperty(ATTR_GROUP_CLAUSE);
    }

    public void setGROUP_CLAUSE(String value)
    {
        setProperty(ATTR_GROUP_CLAUSE, value, 0);
    }

    public String getORDER_CLAUSE()
    {
        return getStringProperty(ATTR_ORDER_CLAUSE);
    }

    public void setORDER_CLAUSE(String value)
    {
        setProperty(ATTR_ORDER_CLAUSE, value, 0);
    }

    public String getFIELD_DEFINITION()
    {
        return getStringProperty(ATTR_FIELD_DEFINITION);
    }

    public void setFIELD_DEFINITION(String value)
    {
        setProperty(ATTR_FIELD_DEFINITION, value, 0);
    }

    public String getSG_DN()
    {
        return getStringProperty(ATTR_SG_DN);
    }

    public void setSG_DN(String value)
    {
        setProperty(ATTR_SG_DN, value, 0);
    }

    public String getSTATUS()
    {
        return getStringProperty(ATTR_STATUS);
    }

    public void setSTATUS(String value)
    {
        setProperty(ATTR_STATUS, value, 0);
    }

    public String getATTRIBUTE1()
    {
        return getStringProperty(ATTR_ATTRIBUTE1);
    }

    public void setATTRIBUTE1(String value)
    {
        setProperty(ATTR_ATTRIBUTE1, value, 0);
    }

    public String getATTRIBUTE2()
    {
        return getStringProperty(ATTR_ATTRIBUTE2);
    }

    public void setATTRIBUTE2(String value)
    {
        setProperty(ATTR_ATTRIBUTE2, value, 0);
    }

    public String getATTRIBUTE3()
    {
        return getStringProperty(ATTR_ATTRIBUTE3);
    }

    public void setATTRIBUTE3(String value)
    {
        setProperty(ATTR_ATTRIBUTE3, value, 0);
    }


    public static com.opentext.lovhandler.LOV_MAPPING getLovMappingObject(int LOV_ID)
    {
        String queryText = "select * from \"LOV_MAPPING\" where \"LOV_ID\" = :LOV_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("LOV_ID", "LOV_MAPPING.LOV_ID", QueryObject.PARAM_INT, new Integer(LOV_ID));//NOPMD
        query.setResultClass(LOV_MAPPING.class);
        return (LOV_MAPPING)query.getObject();
    }

    public static BusObjectIterator<com.opentext.lovhandler.LOV_MAPPING> getLovMappingObjects(int fromLOV_ID, int toLOV_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"LOV_MAPPING\" where \"LOV_ID\" between :fromLOV_ID and :toLOV_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromLOV_ID", "LOV_MAPPING.LOV_ID", QueryObject.PARAM_INT, new Integer(fromLOV_ID));
        query.addParameter("toLOV_ID", "LOV_MAPPING.LOV_ID", QueryObject.PARAM_INT, new Integer(toLOV_ID));
        query.setResultClass(LOV_MAPPING.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.opentext.lovhandler.LOV_MAPPING> getLovMappingObjects(int fromLOV_ID, int toLOV_ID)
    {
        String queryText = "select * from \"LOV_MAPPING\" where \"LOV_ID\" between :fromLOV_ID and :toLOV_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromLOV_ID", "LOV_MAPPING.LOV_ID", QueryObject.PARAM_INT, new Integer(fromLOV_ID));
        query.addParameter("toLOV_ID", "LOV_MAPPING.LOV_ID", QueryObject.PARAM_INT, new Integer(toLOV_ID));
        query.setResultClass(LOV_MAPPING.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.opentext.lovhandler.LOV_MAPPING> getNextLovMappingObjects(int LOV_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"LOV_MAPPING\" where (\"LOV_ID\" > :LOV_ID) order by \"LOV_ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("LOV_ID", "LOV_MAPPING.LOV_ID", QueryObject.PARAM_INT, new Integer(LOV_ID));//NOPMD
        query.setResultClass(LOV_MAPPING.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.opentext.lovhandler.LOV_MAPPING> getPreviousLovMappingObjects(int LOV_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"LOV_MAPPING\" where (\"LOV_ID\" < :LOV_ID) order by \"LOV_ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("LOV_ID", "LOV_MAPPING.LOV_ID", QueryObject.PARAM_INT, new Integer(LOV_ID));//NOPMD
        query.setResultClass(LOV_MAPPING.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
