/*
  This class has been generated by the Code Generator
*/

package com.opentext.lovhandler;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class LOV_MAPPING extends LOV_MAPPINGBase
{
    public LOV_MAPPING()
    {
        this((BusObjectConfig)null);
    }

    public LOV_MAPPING(BusObjectConfig config)
    {
        super(config);
    }

    public static LOV_MAPPING getLOVMappingBySearch(
			String BRANCH, String LOB, String BUSINESS_FUNCTION,
			String PRODUCT, String OPERATION, String FORM_NAME,
			String FORM_FIELD_NAME, String FIELD_TYPE) {
		String queryText = "SELECT * FROM LOV_MAPPING MPLM WHERE"
				+ " MPLM.BRANCH = :BRANCH "
				+ " AND MPLM.LOB = :LOB AND MPLM.BUSINESS_FUNCTION = :BUSINESS_FUNCTION AND "
				+ " MPLM.PRODUCT = :PRODUCT AND MPLM.OPERATION = :OPERATION AND "
				+ " MPLM.FORM_NAME = :FORM_NAME AND MPLM.FORM_FIELD_NAME = :FORM_FIELD_NAME AND "
				+ " MPLM.FIELD_TYPE = :FIELD_TYPE";
		QueryObject query = new QueryObject(queryText);
		query.addParameter("BRANCH", "LOV_MAPPING.BRANCH",
				QueryObject.PARAM_STRING, BRANCH);
		query.addParameter("LOB", "LOV_MAPPING.LOB", QueryObject.PARAM_STRING,
				LOB);
		query.addParameter("BUSINESS_FUNCTION",
				"LOV_MAPPING.BUSINESS_FUNCTION", QueryObject.PARAM_STRING,
				BUSINESS_FUNCTION);
		query.addParameter("PRODUCT", "LOV_MAPPING.PRODUCT",
				QueryObject.PARAM_STRING, PRODUCT);
		query.addParameter("OPERATION", "LOV_MAPPING.OPERATION",
				QueryObject.PARAM_STRING, OPERATION);
		query.addParameter("FORM_NAME", "LOV_MAPPING.FORM_NAME",
				QueryObject.PARAM_STRING, FORM_NAME);
		query.addParameter("FORM_FIELD_NAME", "LOV_MAPPING.FORM_FIELD_NAME",
				QueryObject.PARAM_STRING, FORM_FIELD_NAME);
		query.addParameter("FIELD_TYPE", "LOV_MAPPING.FIELD_TYPE",
				QueryObject.PARAM_STRING, FIELD_TYPE);
		query.setResultClass(LOV_MAPPING.class);
		return (LOV_MAPPING)query.getObject();
	}

}
