/*
  This class has been generated by the Code Generator
*/

package com.opentext.lovhandler;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class LOV_GLOABAL_CONFIGBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_CONFIG_KEY = "CONFIG_KEY";
    public final static String ATTR_CONFIG_VALUE = "CONFIG_VALUE";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(LOV_GLOABAL_CONFIG.class);
            s_classInfo.setTableName("LOV_GLOABAL_CONFIG");
            s_classInfo.setUIDElements(new String[]{ATTR_CONFIG_KEY});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CONFIG_KEY);
                ai.setJavaName(ATTR_CONFIG_KEY);
                ai.setColumnName(ATTR_CONFIG_KEY);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CONFIG_KEY);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CONFIG_VALUE);
                ai.setJavaName(ATTR_CONFIG_VALUE);
                ai.setColumnName(ATTR_CONFIG_VALUE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CONFIG_VALUE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public LOV_GLOABAL_CONFIGBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getCONFIG_KEY()
    {
        return getStringProperty(ATTR_CONFIG_KEY);
    }

    public void setCONFIG_KEY(String value)
    {
        setProperty(ATTR_CONFIG_KEY, value, 0);
    }

    public String getCONFIG_VALUE()
    {
        return getStringProperty(ATTR_CONFIG_VALUE);
    }

    public void setCONFIG_VALUE(String value)
    {
        setProperty(ATTR_CONFIG_VALUE, value, 0);
    }

    public static com.opentext.lovhandler.LOV_GLOABAL_CONFIG getLovGloabalConfigObject(String CONFIG_KEY)
    {
        String queryText = "select * from \"LOV_GLOABAL_CONFIG\" where \"CONFIG_KEY\" = :CONFIG_KEY";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CONFIG_KEY", "LOV_GLOABAL_CONFIG.CONFIG_KEY", QueryObject.PARAM_STRING, CONFIG_KEY);//NOPMD
        query.setResultClass(LOV_GLOABAL_CONFIG.class);
        return (LOV_GLOABAL_CONFIG)query.getObject();
    }

    public static BusObjectIterator<com.opentext.lovhandler.LOV_GLOABAL_CONFIG> getLovGloabalConfigObjects(String fromCONFIG_KEY, String toCONFIG_KEY, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"LOV_GLOABAL_CONFIG\" where \"CONFIG_KEY\" between :fromCONFIG_KEY and :toCONFIG_KEY";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromCONFIG_KEY", "LOV_GLOABAL_CONFIG.CONFIG_KEY", QueryObject.PARAM_STRING, fromCONFIG_KEY);
        query.addParameter("toCONFIG_KEY", "LOV_GLOABAL_CONFIG.CONFIG_KEY", QueryObject.PARAM_STRING, toCONFIG_KEY);
        query.setResultClass(LOV_GLOABAL_CONFIG.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.opentext.lovhandler.LOV_GLOABAL_CONFIG> getLovGloabalConfigObjects(String fromCONFIG_KEY, String toCONFIG_KEY)
    {
        String queryText = "select * from \"LOV_GLOABAL_CONFIG\" where \"CONFIG_KEY\" between :fromCONFIG_KEY and :toCONFIG_KEY";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromCONFIG_KEY", "LOV_GLOABAL_CONFIG.CONFIG_KEY", QueryObject.PARAM_STRING, fromCONFIG_KEY);
        query.addParameter("toCONFIG_KEY", "LOV_GLOABAL_CONFIG.CONFIG_KEY", QueryObject.PARAM_STRING, toCONFIG_KEY);
        query.setResultClass(LOV_GLOABAL_CONFIG.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.opentext.lovhandler.LOV_GLOABAL_CONFIG> getNextLovGloabalConfigObjects(String CONFIG_KEY, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"LOV_GLOABAL_CONFIG\" where (\"CONFIG_KEY\" > :CONFIG_KEY) order by \"CONFIG_KEY\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CONFIG_KEY", "LOV_GLOABAL_CONFIG.CONFIG_KEY", QueryObject.PARAM_STRING, CONFIG_KEY);//NOPMD
        query.setResultClass(LOV_GLOABAL_CONFIG.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.opentext.lovhandler.LOV_GLOABAL_CONFIG> getPreviousLovGloabalConfigObjects(String CONFIG_KEY, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"LOV_GLOABAL_CONFIG\" where (\"CONFIG_KEY\" < :CONFIG_KEY) order by \"CONFIG_KEY\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CONFIG_KEY", "LOV_GLOABAL_CONFIG.CONFIG_KEY", QueryObject.PARAM_STRING, CONFIG_KEY);//NOPMD
        query.setResultClass(LOV_GLOABAL_CONFIG.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
