/*
  This class has been generated by the Code Generator
*/

package com.msig.clintegrations.clappdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class MSIG_SETTLING_AGENT_BANK_DETAILSBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_ID = "ID";
    public final static String ATTR_SA_NAME = "SA_NAME";
    public final static String ATTR_SA_COUNTRY = "SA_COUNTRY";
    public final static String ATTR_SA_BANK_NAME = "SA_BANK_NAME";
    public final static String ATTR_SA_ACC_NO = "SA_ACC_NO";
    public final static String ATTR_SA_CURRENCY = "SA_CURRENCY";
    public final static String ATTR_SWIFT_CODE = "SWIFT_CODE";
    public final static String ATTR_PAYEE_CODE = "PAYEE_CODE";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(MSIG_SETTLING_AGENT_BANK_DETAILS.class);
            s_classInfo.setTableName("MSIG_SETTLING_AGENT_BANK_DETAILS");
            s_classInfo.setUIDElements(new String[]{ATTR_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName(ATTR_ID);
                ai.setColumnName(ATTR_ID);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_ID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SA_NAME);
                ai.setJavaName(ATTR_SA_NAME);
                ai.setColumnName(ATTR_SA_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SA_NAME);
                v.setMaxLength(150);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SA_COUNTRY);
                ai.setJavaName(ATTR_SA_COUNTRY);
                ai.setColumnName(ATTR_SA_COUNTRY);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SA_COUNTRY);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SA_BANK_NAME);
                ai.setJavaName(ATTR_SA_BANK_NAME);
                ai.setColumnName(ATTR_SA_BANK_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SA_BANK_NAME);
                v.setMaxLength(150);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SA_ACC_NO);
                ai.setJavaName(ATTR_SA_ACC_NO);
                ai.setColumnName(ATTR_SA_ACC_NO);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SA_ACC_NO);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SA_CURRENCY);
                ai.setJavaName(ATTR_SA_CURRENCY);
                ai.setColumnName(ATTR_SA_CURRENCY);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SA_CURRENCY);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SWIFT_CODE);
                ai.setJavaName(ATTR_SWIFT_CODE);
                ai.setColumnName(ATTR_SWIFT_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SWIFT_CODE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PAYEE_CODE);
                ai.setJavaName(ATTR_PAYEE_CODE);
                ai.setColumnName(ATTR_PAYEE_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PAYEE_CODE);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public MSIG_SETTLING_AGENT_BANK_DETAILSBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getID()
    {
        return getIntProperty(ATTR_ID);
    }

    public void setID(int value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    public String getSA_NAME()
    {
        return getStringProperty(ATTR_SA_NAME);
    }

    public void setSA_NAME(String value)
    {
        setProperty(ATTR_SA_NAME, value, 0);
    }

    public String getSA_COUNTRY()
    {
        return getStringProperty(ATTR_SA_COUNTRY);
    }

    public void setSA_COUNTRY(String value)
    {
        setProperty(ATTR_SA_COUNTRY, value, 0);
    }

    public String getSA_BANK_NAME()
    {
        return getStringProperty(ATTR_SA_BANK_NAME);
    }

    public void setSA_BANK_NAME(String value)
    {
        setProperty(ATTR_SA_BANK_NAME, value, 0);
    }

    public String getSA_ACC_NO()
    {
        return getStringProperty(ATTR_SA_ACC_NO);
    }

    public void setSA_ACC_NO(String value)
    {
        setProperty(ATTR_SA_ACC_NO, value, 0);
    }

    public String getSA_CURRENCY()
    {
        return getStringProperty(ATTR_SA_CURRENCY);
    }

    public void setSA_CURRENCY(String value)
    {
        setProperty(ATTR_SA_CURRENCY, value, 0);
    }

    public String getSWIFT_CODE()
    {
        return getStringProperty(ATTR_SWIFT_CODE);
    }

    public void setSWIFT_CODE(String value)
    {
        setProperty(ATTR_SWIFT_CODE, value, 0);
    }

    public String getPAYEE_CODE()
    {
        return getStringProperty(ATTR_PAYEE_CODE);
    }

    public void setPAYEE_CODE(String value)
    {
        setProperty(ATTR_PAYEE_CODE, value, 0);
    }

    public static com.msig.clintegrations.clappdb.MSIG_SETTLING_AGENT_BANK_DETAILS getMsigSettlingAgentBankDetailsObject(int ID)
    {
        String queryText = "select * from \"MSIG_SETTLING_AGENT_BANK_DETAILS\" where \"ID\" = :ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "MSIG_SETTLING_AGENT_BANK_DETAILS.ID", QueryObject.PARAM_INT, new Integer(ID));//NOPMD
        query.setResultClass(MSIG_SETTLING_AGENT_BANK_DETAILS.class);
        return (MSIG_SETTLING_AGENT_BANK_DETAILS)query.getObject();
    }

    public static BusObjectIterator<com.msig.clintegrations.clappdb.MSIG_SETTLING_AGENT_BANK_DETAILS> getMsigSettlingAgentBankDetailsObjects(int fromID, int toID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_SETTLING_AGENT_BANK_DETAILS\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "MSIG_SETTLING_AGENT_BANK_DETAILS.ID", QueryObject.PARAM_INT, new Integer(fromID));
        query.addParameter("toID", "MSIG_SETTLING_AGENT_BANK_DETAILS.ID", QueryObject.PARAM_INT, new Integer(toID));
        query.setResultClass(MSIG_SETTLING_AGENT_BANK_DETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.clintegrations.clappdb.MSIG_SETTLING_AGENT_BANK_DETAILS> getMsigSettlingAgentBankDetailsObjects(int fromID, int toID)
    {
        String queryText = "select * from \"MSIG_SETTLING_AGENT_BANK_DETAILS\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "MSIG_SETTLING_AGENT_BANK_DETAILS.ID", QueryObject.PARAM_INT, new Integer(fromID));
        query.addParameter("toID", "MSIG_SETTLING_AGENT_BANK_DETAILS.ID", QueryObject.PARAM_INT, new Integer(toID));
        query.setResultClass(MSIG_SETTLING_AGENT_BANK_DETAILS.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.clintegrations.clappdb.MSIG_SETTLING_AGENT_BANK_DETAILS> getNextMsigSettlingAgentBankDetailsObjects(int ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_SETTLING_AGENT_BANK_DETAILS\" where (\"ID\" > :ID) order by \"ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "MSIG_SETTLING_AGENT_BANK_DETAILS.ID", QueryObject.PARAM_INT, new Integer(ID));//NOPMD
        query.setResultClass(MSIG_SETTLING_AGENT_BANK_DETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }


    public static BusObjectIterator<com.msig.clintegrations.clappdb.MSIG_SETTLING_AGENT_BANK_DETAILS> getPreviousMsigSettlingAgentBankDetailsObjects(int ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_SETTLING_AGENT_BANK_DETAILS\" where (\"ID\" < :ID) order by \"ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "MSIG_SETTLING_AGENT_BANK_DETAILS.ID", QueryObject.PARAM_INT, new Integer(ID));//NOPMD
        query.setResultClass(MSIG_SETTLING_AGENT_BANK_DETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
