/*
  This class has been generated by the Code Generator
*/

package com.msig.clintegrations.clappdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_FK;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class MSIG_CMS_JOURNALPAYMENTBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_JOURNAL_PAYMENT_ID = "JOURNAL_PAYMENT_ID";
    public final static String ATTR_CASE_ID = "CASE_ID";
    public final static String ATTR_PAYMENT_DESCRIPTION = "PAYMENT_DESCRIPTION";
    public final static String ATTR_DEBITOR_CLAIM_NUMBER = "DEBITOR_CLAIM_NUMBER";
    public final static String ATTR_BANK = "BANK";
    public final static String ATTR_PAYMENT_AMOUNT = "PAYMENT_AMOUNT";
    public final static String ATTR_REFERENCE_NUMBER = "REFERENCE_NUMBER";
    public final static String ATTR_PAYEE = "PAYEE";
    private final static String REL_MSIG_CMS_JOURNAL_CREDIT_REQUISITIONObjects = "FK:MSIG_CMS_JOURNALPAYMENT[JOURNAL_PAYMENT_ID]:MSIG_CMS_JOURNAL_CREDIT_REQUISITION[JOURNAL_PAYMENT_ID]";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(MSIG_CMS_JOURNALPAYMENT.class);
            s_classInfo.setTableName("MSIG_CMS_JOURNALPAYMENT");
            s_classInfo.setUIDElements(new String[]{ATTR_JOURNAL_PAYMENT_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_JOURNAL_PAYMENT_ID);
                ai.setJavaName(ATTR_JOURNAL_PAYMENT_ID);
                ai.setColumnName(ATTR_JOURNAL_PAYMENT_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_JOURNAL_PAYMENT_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CASE_ID);
                ai.setJavaName(ATTR_CASE_ID);
                ai.setColumnName(ATTR_CASE_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CASE_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PAYMENT_DESCRIPTION);
                ai.setJavaName(ATTR_PAYMENT_DESCRIPTION);
                ai.setColumnName(ATTR_PAYMENT_DESCRIPTION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PAYMENT_DESCRIPTION);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DEBITOR_CLAIM_NUMBER);
                ai.setJavaName(ATTR_DEBITOR_CLAIM_NUMBER);
                ai.setColumnName(ATTR_DEBITOR_CLAIM_NUMBER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DEBITOR_CLAIM_NUMBER);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BANK);
                ai.setJavaName(ATTR_BANK);
                ai.setColumnName(ATTR_BANK);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BANK);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PAYMENT_AMOUNT);
                ai.setJavaName(ATTR_PAYMENT_AMOUNT);
                ai.setColumnName(ATTR_PAYMENT_AMOUNT);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PAYMENT_AMOUNT);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_REFERENCE_NUMBER);
                ai.setJavaName(ATTR_REFERENCE_NUMBER);
                ai.setColumnName(ATTR_REFERENCE_NUMBER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_REFERENCE_NUMBER);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PAYEE);
                ai.setJavaName(ATTR_PAYEE);
                ai.setColumnName(ATTR_PAYEE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PAYEE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                // relation MSIG_CMS_JOURNAL_CREDIT_REQUISITIONObjects (FK:MSIG_CMS_JOURNALPAYMENT[JOURNAL_PAYMENT_ID]:MSIG_CMS_JOURNAL_CREDIT_REQUISITION[JOURNAL_PAYMENT_ID])
                RelationInfo_FK ri = new RelationInfo_FK(REL_MSIG_CMS_JOURNAL_CREDIT_REQUISITIONObjects);
                ri.setName("MSIG_CMS_JOURNAL_CREDIT_REQUISITIONObjects");
                ri.setLocalAttributes(new String[]{ATTR_JOURNAL_PAYMENT_ID});
                ri.setLocalIsPK(true);
                ri.setRelatedClass(com.msig.clintegrations.clappdb.MSIG_CMS_JOURNAL_CREDIT_REQUISITION.class);
                ri.setRelatedAttributes(new String[]{"JOURNAL_PAYMENT_ID"});//NOPMD
                ri.setRelatedIdentifier("FK:MSIG_CMS_JOURNAL_CREDIT_REQUISITION[JOURNAL_PAYMENT_ID]:MSIG_CMS_JOURNALPAYMENT[JOURNAL_PAYMENT_ID]");
                ri.setLoadMethod("loadMSIG_CMS_JOURNAL_CREDIT_REQUISITIONObjects");
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public MSIG_CMS_JOURNALPAYMENTBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getJOURNAL_PAYMENT_ID()
    {
        return getStringProperty(ATTR_JOURNAL_PAYMENT_ID);
    }

    public void setJOURNAL_PAYMENT_ID(String value)
    {
        setProperty(ATTR_JOURNAL_PAYMENT_ID, value, 0);
    }

    public String getCASE_ID()
    {
        return getStringProperty(ATTR_CASE_ID);
    }

    public void setCASE_ID(String value)
    {
        setProperty(ATTR_CASE_ID, value, 0);
    }

    public String getPAYMENT_DESCRIPTION()
    {
        return getStringProperty(ATTR_PAYMENT_DESCRIPTION);
    }

    public void setPAYMENT_DESCRIPTION(String value)
    {
        setProperty(ATTR_PAYMENT_DESCRIPTION, value, 0);
    }

    public String getDEBITOR_CLAIM_NUMBER()
    {
        return getStringProperty(ATTR_DEBITOR_CLAIM_NUMBER);
    }

    public void setDEBITOR_CLAIM_NUMBER(String value)
    {
        setProperty(ATTR_DEBITOR_CLAIM_NUMBER, value, 0);
    }

    public String getBANK()
    {
        return getStringProperty(ATTR_BANK);
    }

    public void setBANK(String value)
    {
        setProperty(ATTR_BANK, value, 0);
    }

    public String getPAYMENT_AMOUNT()
    {
        return getStringProperty(ATTR_PAYMENT_AMOUNT);
    }

    public void setPAYMENT_AMOUNT(String value)
    {
        setProperty(ATTR_PAYMENT_AMOUNT, value, 0);
    }

    public String getREFERENCE_NUMBER()
    {
        return getStringProperty(ATTR_REFERENCE_NUMBER);
    }

    public void setREFERENCE_NUMBER(String value)
    {
        setProperty(ATTR_REFERENCE_NUMBER, value, 0);
    }

    public String getPAYEE()
    {
        return getStringProperty(ATTR_PAYEE);
    }

    public void setPAYEE(String value)
    {
        setProperty(ATTR_PAYEE, value, 0);
    }

    public BusObjectIterator<MSIG_CMS_JOURNAL_CREDIT_REQUISITION> getMSIG_CMS_JOURNAL_CREDIT_REQUISITIONObjects()
    {
        return getMultiRelationObjects(REL_MSIG_CMS_JOURNAL_CREDIT_REQUISITIONObjects);
    }
    public BusObjectIterator<MSIG_CMS_JOURNAL_CREDIT_REQUISITION> loadMSIG_CMS_JOURNAL_CREDIT_REQUISITIONObjects()
    {
        String queryText = "select * from \"MSIG_CMS_JOURNAL_CREDIT_REQUISITION\" where \"JOURNAL_PAYMENT_ID\" = :JOURNAL_PAYMENT_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("JOURNAL_PAYMENT_ID", "MSIG_CMS_JOURNAL_CREDIT_REQUISITION.JOURNAL_PAYMENT_ID", QueryObject.PARAM_STRING, getJOURNAL_PAYMENT_ID());//NOPMD
        query.setResultClass(MSIG_CMS_JOURNAL_CREDIT_REQUISITION.class);
        return query.getObjects();
    }


    public void addMSIG_CMS_JOURNAL_CREDIT_REQUISITIONObject(MSIG_CMS_JOURNAL_CREDIT_REQUISITION a_MSIG_CMS_JOURNAL_CREDIT_REQUISITION)
    {
        a_MSIG_CMS_JOURNAL_CREDIT_REQUISITION.setJOURNAL_PAYMENT_ID(this.getJOURNAL_PAYMENT_ID());
    }

    public void removeMSIG_CMS_JOURNAL_CREDIT_REQUISITIONObject(MSIG_CMS_JOURNAL_CREDIT_REQUISITION a_MSIG_CMS_JOURNAL_CREDIT_REQUISITION)
    {
        a_MSIG_CMS_JOURNAL_CREDIT_REQUISITION.setNull("JOURNAL_PAYMENT_ID");//NOPMD
    }



}
