/*
  This class has been generated by the Code Generator
*/

package com.msig.clintegrations.clappdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class MSIG_CMS_CLAIMS_RESERVEUPDATE_AUDIT extends MSIG_CMS_CLAIMS_RESERVEUPDATE_AUDITBase
{
    public MSIG_CMS_CLAIMS_RESERVEUPDATE_AUDIT()
    {
        this((BusObjectConfig)null);
    }

    public MSIG_CMS_CLAIMS_RESERVEUPDATE_AUDIT(BusObjectConfig config)
    {
        super(config);
    }

}
