/*
  This class has been generated by the Code Generator
*/

package com.msig.clintegrations.clappdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class MSIG_CMS_JOURNALPAYMENT extends MSIG_CMS_JOURNALPAYMENTBase
{
    public MSIG_CMS_JOURNALPAYMENT()
    {
        this((BusObjectConfig)null);
    }

    public MSIG_CMS_JOURNALPAYMENT(BusObjectConfig config)
    {
        super(config);
    }

    public static int getMsigCmsJournalPayment(String journalPaymentId)
    {      String queryText = "select * from \"MSIG_CMS_JOURNAL_CREDIT_REQUISITION\" where \"JOURNAL_PAYMENT_ID\" = :JOURNAL_PAYMENT_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("JOURNAL_PAYMENT_ID", "MSIG_CMS_JOURNAL_CREDIT_REQUISITION.JOURNAL_PAYMENT_ID", QueryObject.PARAM_STRING, getJOURNAL_PAYMENT_ID());
      
        return (int) 0;
    }

    public static int updateMsigCmsJournalPayment(int Request)
    {
        // TODO implement body
        return (int) 0;
    }

}
