/*
  This class has been generated by the Code Generator
*/

package com.msig.bmsintegrationapp;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;


public abstract class BMS_5336Base extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_FileName = "FileName";
    public final static String ATTR_FilePath = "FilePath";
    public final static String ATTR_ITEM_FROM = "ITEM_FROM";
    public final static String ATTR_ITEM_TO = "ITEM_TO";
    public final static String ATTR_ProductType = "ProductType";
    public final static String ATTR_RiskType = "RiskType";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(BMS_5336.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FileName);
                ai.setJavaName(ATTR_FileName);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FilePath);
                ai.setJavaName(ATTR_FilePath);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ITEM_FROM);
                ai.setJavaName(ATTR_ITEM_FROM);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ITEM_TO);
                ai.setJavaName(ATTR_ITEM_TO);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ProductType);
                ai.setJavaName(ATTR_ProductType);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RiskType);
                ai.setJavaName(ATTR_RiskType);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public BMS_5336Base(BusObjectConfig config)
    {
        super(config);
    }

    public String getFileName()
    {
        return getStringProperty(ATTR_FileName);
    }

    public void setFileName(String value)
    {
        setProperty(ATTR_FileName, value, 0);
    }

    public String getFilePath()
    {
        return getStringProperty(ATTR_FilePath);
    }

    public void setFilePath(String value)
    {
        setProperty(ATTR_FilePath, value, 0);
    }

    public String getITEM_FROM()
    {
        return getStringProperty(ATTR_ITEM_FROM);
    }

    public void setITEM_FROM(String value)
    {
        setProperty(ATTR_ITEM_FROM, value, 0);
    }

    public String getITEM_TO()
    {
        return getStringProperty(ATTR_ITEM_TO);
    }

    public void setITEM_TO(String value)
    {
        setProperty(ATTR_ITEM_TO, value, 0);
    }

    public String getProductType()
    {
        return getStringProperty(ATTR_ProductType);
    }

    public void setProductType(String value)
    {
        setProperty(ATTR_ProductType, value, 0);
    }

    public String getRiskType()
    {
        return getStringProperty(ATTR_RiskType);
    }

    public void setRiskType(String value)
    {
        setProperty(ATTR_RiskType, value, 0);
    }




}
