/*
  This class has been generated by the Code Generator
*/

package com.msig.bmsintegrationapp;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class MSIG_BUSINESS_OBJECTBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_CASE_ID = "CASE_ID";
    public final static String ATTR_BRANCH_ID = "BRANCH_ID";
    public final static String ATTR_BRANCH_NAME = "BRANCH_NAME";
    public final static String ATTR_LOB = "LOB";
    public final static String ATTR_MODULE = "MODULE";
    public final static String ATTR_REQUEST_TYPE = "REQUEST_TYPE";
    public final static String ATTR_POLICY_NUMBER = "POLICY_NUMBER";
    public final static String ATTR_CLAIM_NUMBER = "CLAIM_NUMBER";
    public final static String ATTR_HANDLING_BRANCH_NAME = "HANDLING_BRANCH_NAME";
    public final static String ATTR_HANDLING_BRANCH_ID = "HANDLING_BRANCH_ID";
    public final static String ATTR_ISSUING_BRANCH_NAME = "ISSUING_BRANCH_NAME";
    public final static String ATTR_ISSUING_BTANCH_ID = "ISSUING_BTANCH_ID";
    public final static String ATTR_PROCESS_REFERENCE = "PROCESS_REFERENCE";
    public final static String ATTR_ORGANIZATION_NAME = "ORGANIZATION_NAME";
    public final static String ATTR_APPLICATION_NAME = "APPLICATION_NAME";
    public final static String ATTR_SOURCE = "SOURCE";
    public final static String ATTR_BUSINESS_OBJECT = "BUSINESS_OBJECT";
    public final static String ATTR_REQUESTED_BY = "REQUESTED_BY";
    public final static String ATTR_CURRENT_STATE = "CURRENT_STATE";
    public final static String ATTR_STATUS = "STATUS";
    public final static String ATTR_STATUS_MESSAGE = "STATUS_MESSAGE";
    public final static String ATTR_INITIATED_ON = "INITIATED_ON";
    public final static String ATTR_INITIATED_BY = "INITIATED_BY";
    public final static String ATTR_LAST_MODIFIED_ON = "LAST_MODIFIED_ON";
    public final static String ATTR_LAST_MODIFIED_BY = "LAST_MODIFIED_BY";
    public final static String ATTR_VERSION = "VERSION";
    public final static String ATTR_P400_POSTING_DATE = "P400_POSTING_DATE";
    public final static String ATTR_P400_POSTING_STATUS = "P400_POSTING_STATUS";
    public final static String ATTR_P400_REQUEST = "P400_REQUEST";
    public final static String ATTR_P400_RESPONSE = "P400_RESPONSE";
    public final static String ATTR_CURRENT_ASSIGNEE = "CURRENT_ASSIGNEE";
    public final static String ATTR_PRODUCT = "PRODUCT";
    public final static String ATTR_ACCOUNT_HANDLER = "ACCOUNT_HANDLER";
    public final static String ATTR_INSURED = "INSURED";
    public final static String ATTR_POLICY_TYPE = "POLICY_TYPE";
    public final static String ATTR_AGENT = "AGENT";
    public final static String ATTR_SUMINSURED = "SUMINSURED";
    public final static String ATTR_PREMIUM = "PREMIUM";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(MSIG_BUSINESS_OBJECT.class);
            s_classInfo.setTableName("MSIG_BUSINESS_OBJECT");
            s_classInfo.setUIDElements(new String[]{ATTR_CASE_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CASE_ID);
                ai.setJavaName(ATTR_CASE_ID);
                ai.setColumnName(ATTR_CASE_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CASE_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BRANCH_ID);
                ai.setJavaName(ATTR_BRANCH_ID);
                ai.setColumnName(ATTR_BRANCH_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BRANCH_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BRANCH_NAME);
                ai.setJavaName(ATTR_BRANCH_NAME);
                ai.setColumnName(ATTR_BRANCH_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BRANCH_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LOB);
                ai.setJavaName(ATTR_LOB);
                ai.setColumnName(ATTR_LOB);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LOB);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_MODULE);
                ai.setJavaName(ATTR_MODULE);
                ai.setColumnName(ATTR_MODULE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_MODULE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_REQUEST_TYPE);
                ai.setJavaName(ATTR_REQUEST_TYPE);
                ai.setColumnName(ATTR_REQUEST_TYPE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_REQUEST_TYPE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_POLICY_NUMBER);
                ai.setJavaName(ATTR_POLICY_NUMBER);
                ai.setColumnName(ATTR_POLICY_NUMBER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_POLICY_NUMBER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CLAIM_NUMBER);
                ai.setJavaName(ATTR_CLAIM_NUMBER);
                ai.setColumnName(ATTR_CLAIM_NUMBER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CLAIM_NUMBER);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_HANDLING_BRANCH_NAME);
                ai.setJavaName(ATTR_HANDLING_BRANCH_NAME);
                ai.setColumnName(ATTR_HANDLING_BRANCH_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_HANDLING_BRANCH_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_HANDLING_BRANCH_ID);
                ai.setJavaName(ATTR_HANDLING_BRANCH_ID);
                ai.setColumnName(ATTR_HANDLING_BRANCH_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_HANDLING_BRANCH_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ISSUING_BRANCH_NAME);
                ai.setJavaName(ATTR_ISSUING_BRANCH_NAME);
                ai.setColumnName(ATTR_ISSUING_BRANCH_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ISSUING_BRANCH_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ISSUING_BTANCH_ID);
                ai.setJavaName(ATTR_ISSUING_BTANCH_ID);
                ai.setColumnName(ATTR_ISSUING_BTANCH_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ISSUING_BTANCH_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PROCESS_REFERENCE);
                ai.setJavaName(ATTR_PROCESS_REFERENCE);
                ai.setColumnName(ATTR_PROCESS_REFERENCE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PROCESS_REFERENCE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ORGANIZATION_NAME);
                ai.setJavaName(ATTR_ORGANIZATION_NAME);
                ai.setColumnName(ATTR_ORGANIZATION_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ORGANIZATION_NAME);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_APPLICATION_NAME);
                ai.setJavaName(ATTR_APPLICATION_NAME);
                ai.setColumnName(ATTR_APPLICATION_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_APPLICATION_NAME);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SOURCE);
                ai.setJavaName(ATTR_SOURCE);
                ai.setColumnName(ATTR_SOURCE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SOURCE);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BUSINESS_OBJECT);
                ai.setJavaName(ATTR_BUSINESS_OBJECT);
                ai.setColumnName(ATTR_BUSINESS_OBJECT);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BUSINESS_OBJECT);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_REQUESTED_BY);
                ai.setJavaName(ATTR_REQUESTED_BY);
                ai.setColumnName(ATTR_REQUESTED_BY);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_REQUESTED_BY);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CURRENT_STATE);
                ai.setJavaName(ATTR_CURRENT_STATE);
                ai.setColumnName(ATTR_CURRENT_STATE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CURRENT_STATE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_STATUS);
                ai.setJavaName(ATTR_STATUS);
                ai.setColumnName(ATTR_STATUS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_STATUS);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_STATUS_MESSAGE);
                ai.setJavaName(ATTR_STATUS_MESSAGE);
                ai.setColumnName(ATTR_STATUS_MESSAGE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_STATUS_MESSAGE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_INITIATED_ON);
                ai.setJavaName(ATTR_INITIATED_ON);
                ai.setColumnName(ATTR_INITIATED_ON);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_INITIATED_BY);
                ai.setJavaName(ATTR_INITIATED_BY);
                ai.setColumnName(ATTR_INITIATED_BY);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_INITIATED_BY);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LAST_MODIFIED_ON);
                ai.setJavaName(ATTR_LAST_MODIFIED_ON);
                ai.setColumnName(ATTR_LAST_MODIFIED_ON);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LAST_MODIFIED_BY);
                ai.setJavaName(ATTR_LAST_MODIFIED_BY);
                ai.setColumnName(ATTR_LAST_MODIFIED_BY);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LAST_MODIFIED_BY);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_VERSION);
                ai.setJavaName(ATTR_VERSION);
                ai.setColumnName(ATTR_VERSION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_VERSION);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_P400_POSTING_DATE);
                ai.setJavaName(ATTR_P400_POSTING_DATE);
                ai.setColumnName(ATTR_P400_POSTING_DATE);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_P400_POSTING_STATUS);
                ai.setJavaName(ATTR_P400_POSTING_STATUS);
                ai.setColumnName(ATTR_P400_POSTING_STATUS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_P400_POSTING_STATUS);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_P400_REQUEST);
                ai.setJavaName(ATTR_P400_REQUEST);
                ai.setColumnName(ATTR_P400_REQUEST);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_P400_REQUEST);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_P400_RESPONSE);
                ai.setJavaName(ATTR_P400_RESPONSE);
                ai.setColumnName(ATTR_P400_RESPONSE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_P400_RESPONSE);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CURRENT_ASSIGNEE);
                ai.setJavaName(ATTR_CURRENT_ASSIGNEE);
                ai.setColumnName(ATTR_CURRENT_ASSIGNEE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CURRENT_ASSIGNEE);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT);
                ai.setJavaName(ATTR_PRODUCT);
                ai.setColumnName(ATTR_PRODUCT);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ACCOUNT_HANDLER);
                ai.setJavaName(ATTR_ACCOUNT_HANDLER);
                ai.setColumnName(ATTR_ACCOUNT_HANDLER);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ACCOUNT_HANDLER);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_INSURED);
                ai.setJavaName(ATTR_INSURED);
                ai.setColumnName(ATTR_INSURED);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_INSURED);
                v.setMaxLength(128);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_POLICY_TYPE);
                ai.setJavaName(ATTR_POLICY_TYPE);
                ai.setColumnName(ATTR_POLICY_TYPE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_POLICY_TYPE);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AGENT);
                ai.setJavaName(ATTR_AGENT);
                ai.setColumnName(ATTR_AGENT);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AGENT);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SUMINSURED);
                ai.setJavaName(ATTR_SUMINSURED);
                ai.setColumnName(ATTR_SUMINSURED);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SUMINSURED);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PREMIUM);
                ai.setJavaName(ATTR_PREMIUM);
                ai.setColumnName(ATTR_PREMIUM);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PREMIUM);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public MSIG_BUSINESS_OBJECTBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getCASE_ID()
    {
        return getStringProperty(ATTR_CASE_ID);
    }

    public void setCASE_ID(String value)
    {
        setProperty(ATTR_CASE_ID, value, 0);
    }

    public String getBRANCH_ID()
    {
        return getStringProperty(ATTR_BRANCH_ID);
    }

    public void setBRANCH_ID(String value)
    {
        setProperty(ATTR_BRANCH_ID, value, 0);
    }

    public String getBRANCH_NAME()
    {
        return getStringProperty(ATTR_BRANCH_NAME);
    }

    public void setBRANCH_NAME(String value)
    {
        setProperty(ATTR_BRANCH_NAME, value, 0);
    }

    public String getLOB()
    {
        return getStringProperty(ATTR_LOB);
    }

    public void setLOB(String value)
    {
        setProperty(ATTR_LOB, value, 0);
    }

    public String getMODULE()
    {
        return getStringProperty(ATTR_MODULE);
    }

    public void setMODULE(String value)
    {
        setProperty(ATTR_MODULE, value, 0);
    }

    public String getREQUEST_TYPE()
    {
        return getStringProperty(ATTR_REQUEST_TYPE);
    }

    public void setREQUEST_TYPE(String value)
    {
        setProperty(ATTR_REQUEST_TYPE, value, 0);
    }

    public String getPOLICY_NUMBER()
    {
        return getStringProperty(ATTR_POLICY_NUMBER);
    }

    public void setPOLICY_NUMBER(String value)
    {
        setProperty(ATTR_POLICY_NUMBER, value, 0);
    }

    public String getCLAIM_NUMBER()
    {
        return getStringProperty(ATTR_CLAIM_NUMBER);
    }

    public void setCLAIM_NUMBER(String value)
    {
        setProperty(ATTR_CLAIM_NUMBER, value, 0);
    }

    public String getHANDLING_BRANCH_NAME()
    {
        return getStringProperty(ATTR_HANDLING_BRANCH_NAME);
    }

    public void setHANDLING_BRANCH_NAME(String value)
    {
        setProperty(ATTR_HANDLING_BRANCH_NAME, value, 0);
    }

    public String getHANDLING_BRANCH_ID()
    {
        return getStringProperty(ATTR_HANDLING_BRANCH_ID);
    }

    public void setHANDLING_BRANCH_ID(String value)
    {
        setProperty(ATTR_HANDLING_BRANCH_ID, value, 0);
    }

    public String getISSUING_BRANCH_NAME()
    {
        return getStringProperty(ATTR_ISSUING_BRANCH_NAME);
    }

    public void setISSUING_BRANCH_NAME(String value)
    {
        setProperty(ATTR_ISSUING_BRANCH_NAME, value, 0);
    }

    public String getISSUING_BTANCH_ID()
    {
        return getStringProperty(ATTR_ISSUING_BTANCH_ID);
    }

    public void setISSUING_BTANCH_ID(String value)
    {
        setProperty(ATTR_ISSUING_BTANCH_ID, value, 0);
    }

    public String getPROCESS_REFERENCE()
    {
        return getStringProperty(ATTR_PROCESS_REFERENCE);
    }

    public void setPROCESS_REFERENCE(String value)
    {
        setProperty(ATTR_PROCESS_REFERENCE, value, 0);
    }

    public String getORGANIZATION_NAME()
    {
        return getStringProperty(ATTR_ORGANIZATION_NAME);
    }

    public void setORGANIZATION_NAME(String value)
    {
        setProperty(ATTR_ORGANIZATION_NAME, value, 0);
    }

    public String getAPPLICATION_NAME()
    {
        return getStringProperty(ATTR_APPLICATION_NAME);
    }

    public void setAPPLICATION_NAME(String value)
    {
        setProperty(ATTR_APPLICATION_NAME, value, 0);
    }

    public String getSOURCE()
    {
        return getStringProperty(ATTR_SOURCE);
    }

    public void setSOURCE(String value)
    {
        setProperty(ATTR_SOURCE, value, 0);
    }

    public String getBUSINESS_OBJECT()
    {
        return getStringProperty(ATTR_BUSINESS_OBJECT);
    }

    public void setBUSINESS_OBJECT(String value)
    {
        setProperty(ATTR_BUSINESS_OBJECT, value, 0);
    }

    public String getREQUESTED_BY()
    {
        return getStringProperty(ATTR_REQUESTED_BY);
    }

    public void setREQUESTED_BY(String value)
    {
        setProperty(ATTR_REQUESTED_BY, value, 0);
    }

    public String getCURRENT_STATE()
    {
        return getStringProperty(ATTR_CURRENT_STATE);
    }

    public void setCURRENT_STATE(String value)
    {
        setProperty(ATTR_CURRENT_STATE, value, 0);
    }

    public String getSTATUS()
    {
        return getStringProperty(ATTR_STATUS);
    }

    public void setSTATUS(String value)
    {
        setProperty(ATTR_STATUS, value, 0);
    }

    public String getSTATUS_MESSAGE()
    {
        return getStringProperty(ATTR_STATUS_MESSAGE);
    }

    public void setSTATUS_MESSAGE(String value)
    {
        setProperty(ATTR_STATUS_MESSAGE, value, 0);
    }

    public java.util.Date getINITIATED_ON()
    {
        return getDateTimestampProperty(ATTR_INITIATED_ON);
    }

    public void setINITIATED_ON(java.util.Date value)
    {
        setProperty(ATTR_INITIATED_ON, value, 0);
    }

    public String getINITIATED_BY()
    {
        return getStringProperty(ATTR_INITIATED_BY);
    }

    public void setINITIATED_BY(String value)
    {
        setProperty(ATTR_INITIATED_BY, value, 0);
    }

    public java.util.Date getLAST_MODIFIED_ON()
    {
        return getDateTimestampProperty(ATTR_LAST_MODIFIED_ON);
    }

    public void setLAST_MODIFIED_ON(java.util.Date value)
    {
        setProperty(ATTR_LAST_MODIFIED_ON, value, 0);
    }

    public String getLAST_MODIFIED_BY()
    {
        return getStringProperty(ATTR_LAST_MODIFIED_BY);
    }

    public void setLAST_MODIFIED_BY(String value)
    {
        setProperty(ATTR_LAST_MODIFIED_BY, value, 0);
    }

    public String getVERSION()
    {
        return getStringProperty(ATTR_VERSION);
    }

    public void setVERSION(String value)
    {
        setProperty(ATTR_VERSION, value, 0);
    }

    public java.util.Date getP400_POSTING_DATE()
    {
        return getDateTimestampProperty(ATTR_P400_POSTING_DATE);
    }

    public void setP400_POSTING_DATE(java.util.Date value)
    {
        setProperty(ATTR_P400_POSTING_DATE, value, 0);
    }

    public String getP400_POSTING_STATUS()
    {
        return getStringProperty(ATTR_P400_POSTING_STATUS);
    }

    public void setP400_POSTING_STATUS(String value)
    {
        setProperty(ATTR_P400_POSTING_STATUS, value, 0);
    }

    public String getP400_REQUEST()
    {
        return getStringProperty(ATTR_P400_REQUEST);
    }

    public void setP400_REQUEST(String value)
    {
        setProperty(ATTR_P400_REQUEST, value, 0);
    }

    public String getP400_RESPONSE()
    {
        return getStringProperty(ATTR_P400_RESPONSE);
    }

    public void setP400_RESPONSE(String value)
    {
        setProperty(ATTR_P400_RESPONSE, value, 0);
    }

    public String getCURRENT_ASSIGNEE()
    {
        return getStringProperty(ATTR_CURRENT_ASSIGNEE);
    }

    public void setCURRENT_ASSIGNEE(String value)
    {
        setProperty(ATTR_CURRENT_ASSIGNEE, value, 0);
    }

    public String getPRODUCT()
    {
        return getStringProperty(ATTR_PRODUCT);
    }

    public void setPRODUCT(String value)
    {
        setProperty(ATTR_PRODUCT, value, 0);
    }

    public String getACCOUNT_HANDLER()
    {
        return getStringProperty(ATTR_ACCOUNT_HANDLER);
    }

    public void setACCOUNT_HANDLER(String value)
    {
        setProperty(ATTR_ACCOUNT_HANDLER, value, 0);
    }

    public String getINSURED()
    {
        return getStringProperty(ATTR_INSURED);
    }

    public void setINSURED(String value)
    {
        setProperty(ATTR_INSURED, value, 0);
    }

    public String getPOLICY_TYPE()
    {
        return getStringProperty(ATTR_POLICY_TYPE);
    }

    public void setPOLICY_TYPE(String value)
    {
        setProperty(ATTR_POLICY_TYPE, value, 0);
    }

    public String getAGENT()
    {
        return getStringProperty(ATTR_AGENT);
    }

    public void setAGENT(String value)
    {
        setProperty(ATTR_AGENT, value, 0);
    }

    public String getSUMINSURED()
    {
        return getStringProperty(ATTR_SUMINSURED);
    }

    public void setSUMINSURED(String value)
    {
        setProperty(ATTR_SUMINSURED, value, 0);
    }

    public String getPREMIUM()
    {
        return getStringProperty(ATTR_PREMIUM);
    }

    public void setPREMIUM(String value)
    {
        setProperty(ATTR_PREMIUM, value, 0);
    }

    public static com.msig.bmsintegrationapp.MSIG_BUSINESS_OBJECT getMsigBusinessObjectObject(String CASE_ID)
    {
        String queryText = "select * from \"MSIG_BUSINESS_OBJECT\" where \"CASE_ID\" = :CASE_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CASE_ID", "MSIG_BUSINESS_OBJECT.CASE_ID", QueryObject.PARAM_STRING, CASE_ID);//NOPMD
        query.setResultClass(MSIG_BUSINESS_OBJECT.class);
        return (MSIG_BUSINESS_OBJECT)query.getObject();
    }

    public static BusObjectIterator<com.msig.bmsintegrationapp.MSIG_BUSINESS_OBJECT> getMsigBusinessObjectObjects(String fromCASE_ID, String toCASE_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_BUSINESS_OBJECT\" where \"CASE_ID\" between :fromCASE_ID and :toCASE_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromCASE_ID", "MSIG_BUSINESS_OBJECT.CASE_ID", QueryObject.PARAM_STRING, fromCASE_ID);
        query.addParameter("toCASE_ID", "MSIG_BUSINESS_OBJECT.CASE_ID", QueryObject.PARAM_STRING, toCASE_ID);
        query.setResultClass(MSIG_BUSINESS_OBJECT.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.bmsintegrationapp.MSIG_BUSINESS_OBJECT> getMsigBusinessObjectObjects(String fromCASE_ID, String toCASE_ID)
    {
        String queryText = "select * from \"MSIG_BUSINESS_OBJECT\" where \"CASE_ID\" between :fromCASE_ID and :toCASE_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromCASE_ID", "MSIG_BUSINESS_OBJECT.CASE_ID", QueryObject.PARAM_STRING, fromCASE_ID);
        query.addParameter("toCASE_ID", "MSIG_BUSINESS_OBJECT.CASE_ID", QueryObject.PARAM_STRING, toCASE_ID);
        query.setResultClass(MSIG_BUSINESS_OBJECT.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.bmsintegrationapp.MSIG_BUSINESS_OBJECT> getNextMsigBusinessObjectObjects(String CASE_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_BUSINESS_OBJECT\" where (\"CASE_ID\" > :CASE_ID) order by \"CASE_ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CASE_ID", "MSIG_BUSINESS_OBJECT.CASE_ID", QueryObject.PARAM_STRING, CASE_ID);//NOPMD
        query.setResultClass(MSIG_BUSINESS_OBJECT.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.bmsintegrationapp.MSIG_BUSINESS_OBJECT> getPreviousMsigBusinessObjectObjects(String CASE_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_BUSINESS_OBJECT\" where (\"CASE_ID\" < :CASE_ID) order by \"CASE_ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CASE_ID", "MSIG_BUSINESS_OBJECT.CASE_ID", QueryObject.PARAM_STRING, CASE_ID);//NOPMD
        query.setResultClass(MSIG_BUSINESS_OBJECT.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
