/*
  This class has been generated by the Code Generator
*/

package com.msig.bmsintegrationapp;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class MSIG_USERS_MASTER extends MSIG_USERS_MASTERBase
{
    public MSIG_USERS_MASTER()
    {
        this((BusObjectConfig)null);
    }

    public MSIG_USERS_MASTER(BusObjectConfig config)
    {
        super(config);
    }

}
