/*
  This class has been generated by the Code Generator
*/

package com.msig.masterdata;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class MSIG_ROLES_PRIORITY_SEQBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_APPLICATION = "APPLICATION";
    public final static String ATTR_LOB_CODE = "LOB_CODE";
    public final static String ATTR_ROLE_CODE = "ROLE_CODE";
    public final static String ATTR_SEQUENCE = "SEQUENCE";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(MSIG_ROLES_PRIORITY_SEQ.class);
            s_classInfo.setTableName("MSIG_ROLES_PRIORITY_SEQ");
            s_classInfo.setUIDElements(new String[]{ATTR_APPLICATION, ATTR_LOB_CODE, ATTR_ROLE_CODE});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_APPLICATION);
                ai.setJavaName(ATTR_APPLICATION);
                ai.setColumnName(ATTR_APPLICATION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_APPLICATION);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LOB_CODE);
                ai.setJavaName(ATTR_LOB_CODE);
                ai.setColumnName(ATTR_LOB_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LOB_CODE);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ROLE_CODE);
                ai.setJavaName(ATTR_ROLE_CODE);
                ai.setColumnName(ATTR_ROLE_CODE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ROLE_CODE);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SEQUENCE);
                ai.setJavaName(ATTR_SEQUENCE);
                ai.setColumnName(ATTR_SEQUENCE);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_SEQUENCE);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public MSIG_ROLES_PRIORITY_SEQBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getAPPLICATION()
    {
        return getStringProperty(ATTR_APPLICATION);
    }

    public void setAPPLICATION(String value)
    {
        setProperty(ATTR_APPLICATION, value, 0);
    }

    public String getLOB_CODE()
    {
        return getStringProperty(ATTR_LOB_CODE);
    }

    public void setLOB_CODE(String value)
    {
        setProperty(ATTR_LOB_CODE, value, 0);
    }

    public String getROLE_CODE()
    {
        return getStringProperty(ATTR_ROLE_CODE);
    }

    public void setROLE_CODE(String value)
    {
        setProperty(ATTR_ROLE_CODE, value, 0);
    }

    public double getSEQUENCE()
    {
        return getDoubleProperty(ATTR_SEQUENCE);
    }

    public void setSEQUENCE(double value)
    {
        setProperty(ATTR_SEQUENCE, value, 0);
    }

    public static com.msig.masterdata.MSIG_ROLES_PRIORITY_SEQ getMsigRolesPrioritySeqObject(String APPLICATION, String LOB_CODE, String ROLE_CODE)
    {
        String queryText = "select * from \"MSIG_ROLES_PRIORITY_SEQ\" where \"APPLICATION\" = :APPLICATION and \"LOB_CODE\" = :LOB_CODE and \"ROLE_CODE\" = :ROLE_CODE";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("APPLICATION", "MSIG_ROLES_PRIORITY_SEQ.APPLICATION", QueryObject.PARAM_STRING, APPLICATION);//NOPMD
        query.addParameter("LOB_CODE", "MSIG_ROLES_PRIORITY_SEQ.LOB_CODE", QueryObject.PARAM_STRING, LOB_CODE);//NOPMD
        query.addParameter("ROLE_CODE", "MSIG_ROLES_PRIORITY_SEQ.ROLE_CODE", QueryObject.PARAM_STRING, ROLE_CODE);//NOPMD
        query.setResultClass(MSIG_ROLES_PRIORITY_SEQ.class);
        return (MSIG_ROLES_PRIORITY_SEQ)query.getObject();
    }

    public static BusObjectIterator<com.msig.masterdata.MSIG_ROLES_PRIORITY_SEQ> getMsigRolesPrioritySeqObjects(String fromAPPLICATION, String toAPPLICATION, String fromLOB_CODE, String toLOB_CODE, String fromROLE_CODE, String toROLE_CODE, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_ROLES_PRIORITY_SEQ\" where \"APPLICATION\" between :fromAPPLICATION and :toAPPLICATION and \"LOB_CODE\" between :fromLOB_CODE and :toLOB_CODE and \"ROLE_CODE\" between :fromROLE_CODE and :toROLE_CODE";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromAPPLICATION", "MSIG_ROLES_PRIORITY_SEQ.APPLICATION", QueryObject.PARAM_STRING, fromAPPLICATION);
        query.addParameter("toAPPLICATION", "MSIG_ROLES_PRIORITY_SEQ.APPLICATION", QueryObject.PARAM_STRING, toAPPLICATION);
        query.addParameter("fromLOB_CODE", "MSIG_ROLES_PRIORITY_SEQ.LOB_CODE", QueryObject.PARAM_STRING, fromLOB_CODE);
        query.addParameter("toLOB_CODE", "MSIG_ROLES_PRIORITY_SEQ.LOB_CODE", QueryObject.PARAM_STRING, toLOB_CODE);
        query.addParameter("fromROLE_CODE", "MSIG_ROLES_PRIORITY_SEQ.ROLE_CODE", QueryObject.PARAM_STRING, fromROLE_CODE);
        query.addParameter("toROLE_CODE", "MSIG_ROLES_PRIORITY_SEQ.ROLE_CODE", QueryObject.PARAM_STRING, toROLE_CODE);
        query.setResultClass(MSIG_ROLES_PRIORITY_SEQ.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.masterdata.MSIG_ROLES_PRIORITY_SEQ> getMsigRolesPrioritySeqObjects(String fromAPPLICATION, String toAPPLICATION, String fromLOB_CODE, String toLOB_CODE, String fromROLE_CODE, String toROLE_CODE)
    {
        String queryText = "select * from \"MSIG_ROLES_PRIORITY_SEQ\" where \"APPLICATION\" between :fromAPPLICATION and :toAPPLICATION and \"LOB_CODE\" between :fromLOB_CODE and :toLOB_CODE and \"ROLE_CODE\" between :fromROLE_CODE and :toROLE_CODE";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromAPPLICATION", "MSIG_ROLES_PRIORITY_SEQ.APPLICATION", QueryObject.PARAM_STRING, fromAPPLICATION);
        query.addParameter("toAPPLICATION", "MSIG_ROLES_PRIORITY_SEQ.APPLICATION", QueryObject.PARAM_STRING, toAPPLICATION);
        query.addParameter("fromLOB_CODE", "MSIG_ROLES_PRIORITY_SEQ.LOB_CODE", QueryObject.PARAM_STRING, fromLOB_CODE);
        query.addParameter("toLOB_CODE", "MSIG_ROLES_PRIORITY_SEQ.LOB_CODE", QueryObject.PARAM_STRING, toLOB_CODE);
        query.addParameter("fromROLE_CODE", "MSIG_ROLES_PRIORITY_SEQ.ROLE_CODE", QueryObject.PARAM_STRING, fromROLE_CODE);
        query.addParameter("toROLE_CODE", "MSIG_ROLES_PRIORITY_SEQ.ROLE_CODE", QueryObject.PARAM_STRING, toROLE_CODE);
        query.setResultClass(MSIG_ROLES_PRIORITY_SEQ.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.masterdata.MSIG_ROLES_PRIORITY_SEQ> getNextMsigRolesPrioritySeqObjects(String APPLICATION, String LOB_CODE, String ROLE_CODE, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_ROLES_PRIORITY_SEQ\" where (\"APPLICATION\" > :APPLICATION) or (\"APPLICATION\" = :APPLICATION and \"LOB_CODE\" > :LOB_CODE) or (\"APPLICATION\" = :APPLICATION and \"LOB_CODE\" = :LOB_CODE and \"ROLE_CODE\" > :ROLE_CODE) order by \"APPLICATION\" asc, \"LOB_CODE\" asc, \"ROLE_CODE\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("APPLICATION", "MSIG_ROLES_PRIORITY_SEQ.APPLICATION", QueryObject.PARAM_STRING, APPLICATION);//NOPMD
        query.addParameter("LOB_CODE", "MSIG_ROLES_PRIORITY_SEQ.LOB_CODE", QueryObject.PARAM_STRING, LOB_CODE);//NOPMD
        query.addParameter("ROLE_CODE", "MSIG_ROLES_PRIORITY_SEQ.ROLE_CODE", QueryObject.PARAM_STRING, ROLE_CODE);//NOPMD
        query.setResultClass(MSIG_ROLES_PRIORITY_SEQ.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.masterdata.MSIG_ROLES_PRIORITY_SEQ> getPreviousMsigRolesPrioritySeqObjects(String APPLICATION, String LOB_CODE, String ROLE_CODE, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"MSIG_ROLES_PRIORITY_SEQ\" where (\"APPLICATION\" < :APPLICATION) or (\"APPLICATION\" = :APPLICATION and \"LOB_CODE\" < :LOB_CODE) or (\"APPLICATION\" = :APPLICATION and \"LOB_CODE\" = :LOB_CODE and \"ROLE_CODE\" < :ROLE_CODE) order by \"APPLICATION\" desc, \"LOB_CODE\" desc, \"ROLE_CODE\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("APPLICATION", "MSIG_ROLES_PRIORITY_SEQ.APPLICATION", QueryObject.PARAM_STRING, APPLICATION);//NOPMD
        query.addParameter("LOB_CODE", "MSIG_ROLES_PRIORITY_SEQ.LOB_CODE", QueryObject.PARAM_STRING, LOB_CODE);//NOPMD
        query.addParameter("ROLE_CODE", "MSIG_ROLES_PRIORITY_SEQ.ROLE_CODE", QueryObject.PARAM_STRING, ROLE_CODE);//NOPMD
        query.setResultClass(MSIG_ROLES_PRIORITY_SEQ.class);
        query.setCursor(cursor);
        return query.getObjects();
    }


}
