/*
  This class has been generated by the Code Generator
 */

package com.msig.masterdata;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;

public class MSIG_AWUS_CONDITIONS extends MSIG_AWUS_CONDITIONSBase {
	public MSIG_AWUS_CONDITIONS() {
		this((BusObjectConfig) null);
	}

	public MSIG_AWUS_CONDITIONS(BusObjectConfig config) {
		super(config);
	}

}
