/*
  This class has been generated by the Code Generator
*/

package com.msig.masterdata;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_FK;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public class MSIG_DOCUMENT_TYPE_SECURITY_PARTS extends MSIG_DOCUMENT_TYPE_SECURITY_PARTSBase
{
    public MSIG_DOCUMENT_TYPE_SECURITY_PARTS()
    {
        this((BusObjectConfig)null);
    }

    public MSIG_DOCUMENT_TYPE_SECURITY_PARTS(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.msig.masterdata.MSIG_DOCUMENT_TYPE_SECURITY_PARTS> getMsigDocumentTypeSecurityPartsByParentId(int CONFIG_ID)
    {
        String queryText = "select * from \"MSIG_DOCUMENT_TYPE_SECURITY_PARTS\" where \"CONFIG_ID\" = :CONFIG_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CONFIG_ID", "MSIG_DOCUMENT_TYPE_SECURITY_PARTS.CONFIG_ID", QueryObject.PARAM_INT, new Integer(CONFIG_ID));//NOPMD
        query.setResultClass(MSIG_DOCUMENT_TYPE_SECURITY_PARTS.class);
        return  query.getObjects();
    }


}
