/*
  This class has been generated by the Code Generator
*/

package com.msig.masterdata;

import java.util.Date;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class MSIG_INCIDENT_CODES extends MSIG_INCIDENT_CODESBase
{
    public MSIG_INCIDENT_CODES()
    {
        this((BusObjectConfig)null);
    }

    public MSIG_INCIDENT_CODES(BusObjectConfig config)
    {
        super(config);
    }

    @Override
    public void onBeforeInsert() {
    	super.onBeforeInsert();
    	
    	if (this.getSTATUS().equals("")) {
    		this.setSTATUS("A");
    	}
    	
    	this.setCREATED_BY(MasterDataUtil.getUserName());
    	this.setCREATED_ON(new Date());
    	this.setMODIFIED_BY(MasterDataUtil.getUserName());
    	this.setMODIFIED_ON(new Date());
    }
    
    @Override
    public void onBeforeUpdate() {
    	super.onBeforeUpdate();
    	this.setMODIFIED_BY(MasterDataUtil.getUserName());
    	this.setMODIFIED_ON(new Date());
    }
    
    public static BusObjectIterator<com.msig.masterdata.MSIG_INCIDENT_CODES> searchIncidentCodeMaster(String INCIDENT_CODE, String INCIDENT_DESC)
    {
        INCIDENT_CODE = "%" + INCIDENT_CODE + "%";
        INCIDENT_DESC = "%" + INCIDENT_DESC + "%";
        
        String queryText = "SELECT * FROM MSIG_INCIDENT_CODES WHERE INCIDENT_CODE LIKE :INCIDENT_CODE AND INCIDENT_DESC LIKE :INCIDENT_DESC";
        
        QueryObject query = new QueryObject(queryText);
        query.addParameter("INCIDENT_CODE", "MSIG_INCIDENT_CODES.INCIDENT_CODE", QueryObject.PARAM_STRING, INCIDENT_CODE);
        query.addParameter("INCIDENT_DESC", "MSIG_INCIDENT_CODES.INCIDENT_DESC", QueryObject.PARAM_STRING, INCIDENT_DESC);
        
        query.setResultClass(MSIG_INCIDENT_CODES.class);
        
    	return query.getObjects();
    }

}
