/*
  This class has been generated by the Code Generator
*/

package com.msig.masterdata;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class PRODUCT_DETAILSBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_ID = "ID";
    public final static String ATTR_PRODUCT_TYPE = "PRODUCT_TYPE";
    public final static String ATTR_PRODUCT_NAME = "PRODUCT_NAME";
    public final static String ATTR_RISK_TYPE = "RISK_TYPE";
    public final static String ATTR_RISK_NAME = "RISK_NAME";
    public final static String ATTR_RISK_GROUPING = "RISK_GROUPING";
    public final static String ATTR_PREMIUM_CLASS = "PREMIUM_CLASS";
    public final static String ATTR_RISK_SCREEN = "RISK_SCREEN";
    public final static String ATTR_RISK_SCREEN_NM = "RISK_SCREEN_NM";
    public final static String ATTR_STATISTICS_SCREEN = "STATISTICS_SCREEN";
    public final static String ATTR_STAT_SCREEN_NM = "STAT_SCREEN_NM";
    public final static String ATTR_BMS_LOB = "BMS_LOB";
    public final static String ATTR_CMS_LOB = "CMS_LOB";
    public final static String ATTR_MUL_RISKS_FLAG = "MUL_RISKS_FLAG";
    public final static String ATTR_PACKAGE = "PACKAGE";
    public final static String ATTR_ATTRIBUTE1 = "ATTRIBUTE1";
    public final static String ATTR_ATTRIBUTE2 = "ATTRIBUTE2";
    public final static String ATTR_ATTRIBUTE3 = "ATTRIBUTE3";
    public final static String ATTR_ISFASTTRACK = "ISFASTTRACK";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(PRODUCT_DETAILS.class);
            s_classInfo.setTableName("PRODUCT_DETAILS");
            s_classInfo.setUIDElements(new String[]{ATTR_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName(ATTR_ID);
                ai.setColumnName(ATTR_ID);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_ID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT_TYPE);
                ai.setJavaName(ATTR_PRODUCT_TYPE);
                ai.setColumnName(ATTR_PRODUCT_TYPE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT_TYPE);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PRODUCT_NAME);
                ai.setJavaName(ATTR_PRODUCT_NAME);
                ai.setColumnName(ATTR_PRODUCT_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PRODUCT_NAME);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RISK_TYPE);
                ai.setJavaName(ATTR_RISK_TYPE);
                ai.setColumnName(ATTR_RISK_TYPE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RISK_TYPE);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RISK_NAME);
                ai.setJavaName(ATTR_RISK_NAME);
                ai.setColumnName(ATTR_RISK_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RISK_NAME);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RISK_GROUPING);
                ai.setJavaName(ATTR_RISK_GROUPING);
                ai.setColumnName(ATTR_RISK_GROUPING);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RISK_GROUPING);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PREMIUM_CLASS);
                ai.setJavaName(ATTR_PREMIUM_CLASS);
                ai.setColumnName(ATTR_PREMIUM_CLASS);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PREMIUM_CLASS);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RISK_SCREEN);
                ai.setJavaName(ATTR_RISK_SCREEN);
                ai.setColumnName(ATTR_RISK_SCREEN);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RISK_SCREEN);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RISK_SCREEN_NM);
                ai.setJavaName(ATTR_RISK_SCREEN_NM);
                ai.setColumnName(ATTR_RISK_SCREEN_NM);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RISK_SCREEN_NM);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_STATISTICS_SCREEN);
                ai.setJavaName(ATTR_STATISTICS_SCREEN);
                ai.setColumnName(ATTR_STATISTICS_SCREEN);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_STATISTICS_SCREEN);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_STAT_SCREEN_NM);
                ai.setJavaName(ATTR_STAT_SCREEN_NM);
                ai.setColumnName(ATTR_STAT_SCREEN_NM);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_STAT_SCREEN_NM);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BMS_LOB);
                ai.setJavaName(ATTR_BMS_LOB);
                ai.setColumnName(ATTR_BMS_LOB);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BMS_LOB);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CMS_LOB);
                ai.setJavaName(ATTR_CMS_LOB);
                ai.setColumnName(ATTR_CMS_LOB);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CMS_LOB);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_MUL_RISKS_FLAG);
                ai.setJavaName(ATTR_MUL_RISKS_FLAG);
                ai.setColumnName(ATTR_MUL_RISKS_FLAG);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_MUL_RISKS_FLAG);
                v.setMaxLength(1);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PACKAGE);
                ai.setJavaName(ATTR_PACKAGE);
                ai.setColumnName(ATTR_PACKAGE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PACKAGE);
                v.setMaxLength(1);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ATTRIBUTE1);
                ai.setJavaName(ATTR_ATTRIBUTE1);
                ai.setColumnName(ATTR_ATTRIBUTE1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ATTRIBUTE1);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ATTRIBUTE2);
                ai.setJavaName(ATTR_ATTRIBUTE2);
                ai.setColumnName(ATTR_ATTRIBUTE2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ATTRIBUTE2);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ATTRIBUTE3);
                ai.setJavaName(ATTR_ATTRIBUTE3);
                ai.setColumnName(ATTR_ATTRIBUTE3);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ATTRIBUTE3);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ISFASTTRACK);
                ai.setJavaName(ATTR_ISFASTTRACK);
                ai.setColumnName(ATTR_ISFASTTRACK);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ISFASTTRACK);
                v.setMaxLength(1);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public PRODUCT_DETAILSBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getID()
    {
        return getIntProperty(ATTR_ID);
    }

    public void setID(int value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    public String getPRODUCT_TYPE()
    {
        return getStringProperty(ATTR_PRODUCT_TYPE);
    }

    public void setPRODUCT_TYPE(String value)
    {
        setProperty(ATTR_PRODUCT_TYPE, value, 0);
    }

    public String getPRODUCT_NAME()
    {
        return getStringProperty(ATTR_PRODUCT_NAME);
    }

    public void setPRODUCT_NAME(String value)
    {
        setProperty(ATTR_PRODUCT_NAME, value, 0);
    }

    public String getRISK_TYPE()
    {
        return getStringProperty(ATTR_RISK_TYPE);
    }

    public void setRISK_TYPE(String value)
    {
        setProperty(ATTR_RISK_TYPE, value, 0);
    }

    public String getRISK_NAME()
    {
        return getStringProperty(ATTR_RISK_NAME);
    }

    public void setRISK_NAME(String value)
    {
        setProperty(ATTR_RISK_NAME, value, 0);
    }

    public String getRISK_GROUPING()
    {
        return getStringProperty(ATTR_RISK_GROUPING);
    }

    public void setRISK_GROUPING(String value)
    {
        setProperty(ATTR_RISK_GROUPING, value, 0);
    }

    public String getPREMIUM_CLASS()
    {
        return getStringProperty(ATTR_PREMIUM_CLASS);
    }

    public void setPREMIUM_CLASS(String value)
    {
        setProperty(ATTR_PREMIUM_CLASS, value, 0);
    }

    public String getRISK_SCREEN()
    {
        return getStringProperty(ATTR_RISK_SCREEN);
    }

    public void setRISK_SCREEN(String value)
    {
        setProperty(ATTR_RISK_SCREEN, value, 0);
    }

    public String getRISK_SCREEN_NM()
    {
        return getStringProperty(ATTR_RISK_SCREEN_NM);
    }

    public void setRISK_SCREEN_NM(String value)
    {
        setProperty(ATTR_RISK_SCREEN_NM, value, 0);
    }

    public String getSTATISTICS_SCREEN()
    {
        return getStringProperty(ATTR_STATISTICS_SCREEN);
    }

    public void setSTATISTICS_SCREEN(String value)
    {
        setProperty(ATTR_STATISTICS_SCREEN, value, 0);
    }

    public String getSTAT_SCREEN_NM()
    {
        return getStringProperty(ATTR_STAT_SCREEN_NM);
    }

    public void setSTAT_SCREEN_NM(String value)
    {
        setProperty(ATTR_STAT_SCREEN_NM, value, 0);
    }

    public String getBMS_LOB()
    {
        return getStringProperty(ATTR_BMS_LOB);
    }

    public void setBMS_LOB(String value)
    {
        setProperty(ATTR_BMS_LOB, value, 0);
    }

    public String getCMS_LOB()
    {
        return getStringProperty(ATTR_CMS_LOB);
    }

    public void setCMS_LOB(String value)
    {
        setProperty(ATTR_CMS_LOB, value, 0);
    }

    public String getMUL_RISKS_FLAG()
    {
        return getStringProperty(ATTR_MUL_RISKS_FLAG);
    }

    public void setMUL_RISKS_FLAG(String value)
    {
        setProperty(ATTR_MUL_RISKS_FLAG, value, 0);
    }

    public String getPACKAGE()
    {
        return getStringProperty(ATTR_PACKAGE);
    }

    public void setPACKAGE(String value)
    {
        setProperty(ATTR_PACKAGE, value, 0);
    }

    public String getATTRIBUTE1()
    {
        return getStringProperty(ATTR_ATTRIBUTE1);
    }

    public void setATTRIBUTE1(String value)
    {
        setProperty(ATTR_ATTRIBUTE1, value, 0);
    }

    public String getATTRIBUTE2()
    {
        return getStringProperty(ATTR_ATTRIBUTE2);
    }

    public void setATTRIBUTE2(String value)
    {
        setProperty(ATTR_ATTRIBUTE2, value, 0);
    }

    public String getATTRIBUTE3()
    {
        return getStringProperty(ATTR_ATTRIBUTE3);
    }

    public void setATTRIBUTE3(String value)
    {
        setProperty(ATTR_ATTRIBUTE3, value, 0);
    }

    public String getISFASTTRACK()
    {
        return getStringProperty(ATTR_ISFASTTRACK);
    }

    public void setISFASTTRACK(String value)
    {
        setProperty(ATTR_ISFASTTRACK, value, 0);
    }

    public static BusObjectIterator<com.msig.masterdata.PRODUCT_DETAILS> getNextProductDetailsObjects(int ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PRODUCT_DETAILS\" where (\"ID\" > :ID) order by \"ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "PRODUCT_DETAILS.ID", QueryObject.PARAM_INT, new Integer(ID));//NOPMD
        query.setResultClass(PRODUCT_DETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.masterdata.PRODUCT_DETAILS> getPreviousProductDetailsObjects(int ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PRODUCT_DETAILS\" where (\"ID\" < :ID) order by \"ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "PRODUCT_DETAILS.ID", QueryObject.PARAM_INT, new Integer(ID));//NOPMD
        query.setResultClass(PRODUCT_DETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.msig.masterdata.PRODUCT_DETAILS getProductDetailsObject(int ID)
    {
        String queryText = "select * from \"PRODUCT_DETAILS\" where \"ID\" = :ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "PRODUCT_DETAILS.ID", QueryObject.PARAM_INT, new Integer(ID));//NOPMD
        query.setResultClass(PRODUCT_DETAILS.class);
        return (PRODUCT_DETAILS)query.getObject();
    }

    public static BusObjectIterator<com.msig.masterdata.PRODUCT_DETAILS> getProductDetailsObjects(int fromID, int toID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PRODUCT_DETAILS\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "PRODUCT_DETAILS.ID", QueryObject.PARAM_INT, new Integer(fromID));
        query.addParameter("toID", "PRODUCT_DETAILS.ID", QueryObject.PARAM_INT, new Integer(toID));
        query.setResultClass(PRODUCT_DETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.msig.masterdata.PRODUCT_DETAILS> getProductDetailsObjects(int fromID, int toID)
    {
        String queryText = "select * from \"PRODUCT_DETAILS\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "PRODUCT_DETAILS.ID", QueryObject.PARAM_INT, new Integer(fromID));
        query.addParameter("toID", "PRODUCT_DETAILS.ID", QueryObject.PARAM_INT, new Integer(toID));
        query.setResultClass(PRODUCT_DETAILS.class);
        return query.getObjects();
    }

}
